### ISSUE TITLE
Managers: Add default property

### ISSUE THREAD

**Issue by Smaug6739** [Sheweny/framework#76]
CommandManager : Add default data for commands :

- [x] Default adminOnly
- [x] Default category
- [x] Default channel
- [x] Default client permissions
- [x] Default cooldown
- [x] Default example
- [x] Default type
- [x] Default usage
- [x] Default userPermissions

InhibitorsManagers: Add default date for inhibitors : 

- [x] Default priority
- [x] Default type

Events manager : Add default data for events : 

- [x] Default emitter
- [x] Default once

**Comment by Jirasi25** [comment]
> help wanted
