### ISSUE TITLE
Can't use a channelTypes parameter in options of slash commands 

### ISSUE THREAD

**Issue by Dercraker** [Sheweny/framework#77]
**Please describe the problem you are having in as much detail as possible:**
when I want to set the channelTypes parameter for the command slash options I get an error saying that channeltypes is not known in the ApplicationCommandeChoiceData type 
![image](https://user-images.githubusercontent.com/46059868/147211420-73c19ef1-c70a-4489-ad2d-110b642ba376.png)

**Include a reproducible code sample here, if possible:**

```ts
import { Command } from "sheweny"
import type { ShewenyClient } from "sheweny"
import type { CommandInteraction } from "discord.js"



export class ExampleCommand extends Command {
    constructor(client: ShewenyClient) {
        super(client, {
            name: '',
            description: '',
            usage : '',
            examples : '',
            // type: '', //* Default type is SLASH_COMMAND
            options : [{
                    type : 'STRING',
                    name: 'commande',
                    description: '',
                    autocomplete : false,
                    required : false,
                    choices : [],
                    channelTypes : ['GUILD_TEXT','GUILD_CATEGORY','GUILD_NEWS',],
            }],
            defaultPermission : true,
            // category: '', //* Default category is InDev
            // channel : '', //* Default Channel is GUILD
            // cooldown : , //* Default cooldown set at 2sec
            // adminsOnly : , //* Default value is false 
            userPermissions : [],
            clientPermissions : []
        });
    }
    execute(interaction : CommandInteraction) {
        
        return interaction.reply({
            content : 'Send'
        }) 
    }
}


```

**Further details:**

- Sheweny version: 3.3.2
- Node.js version: 17.1.0
- Operating system: WIN 11
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: 32767
- mode: development
- other: none
- Using cli (@sheweny/cli) : no

**Comment by Smaug6739** [comment]
Hi, thank you for the issue !

The key `channelTypes` can only work if the type of the argument is `CHANNEL`. 

Note that with the "CHANNEL" type option you can't have a `choices` key in your object.
